//
// Created by 澤田開杜 on 2020/02/08.
//

#ifndef PRC_WATERTOWER_VARIABLES_H
#define PRC_WATERTOWER_VARIABLES_H
#define DETECTION_STANDARD_DISTANCE_MAX 75
#define DETECTION_STANDARD_DISTANCE_MIN 30
#define WAITING_FOR_TRAIN_TIME 3000 // 3s
#define WAITING_FOR_WATER_SUPPLY 5000 // 5s
#define SERVO_ANGLE 120
#define TIMES 100
#endif //PRC_WATERTOWER_VARIABLES_H
