//
// Created by 澤田開杜 on 2020/02/08.
//

#ifndef PRC_WATERTOWER_VARIABLES_H
#define PRC_WATERTOWER_VARIABLES_H
#define DETECTION_STANDARD_DISTANCE 100
#define WAITING_TIME 10000 // 10s
#define SERVO_ANGLE 90
#define TIMES 100
#endif //PRC_WATERTOWER_VARIABLES_H
