//
// Created by 澤田開杜 on 2020/02/08.
//

#ifndef PRC_WATERTOWER_VARIABLES_H
#define PRC_WATERTOWER_VARIABLES_H
#define DETECTION_STANDARD_DISTANCE_MAX 50
#define DETECTION_STANDARD_DISTANCE_MIN 2
#define WAITING_FOR_TRAIN_TIME 2000 // 2s
#define WAITING_FOR_WATER_SUPPLY 5000 // 5s
#define SERVO_ANGLE 120
#define TIMES 100
#endif //PRC_WATERTOWER_VARIABLES_H
